# Generated by Django 3.2 on 2023-02-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('content', models.TextField()),
                ('messaged_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-messaged_on'],
            },
        ),
    ]
